#' Change font of time series values
#'
#' `timeseries_style()` changes the font of time series values based on the
#' indicator type it is:
#'
#' * bold: reported
#' * normal: estimated
#' * faded: imputed or projected
#'
#' @inheritParams write_main_df
#'
timeseries_style <- function(df, wb, sheet_name, start_row, start_col, ind, year, type_col) {

  wide_df <- df %>%
    dplyr::ungroup() %>%
    dplyr::select(.data[[ind]],.data[[year]], .data[[type_col]]) %>%
    dplyr::filter(!stringr::str_detect(.data[[ind]], "^hpop_healthier")) %>%
    dplyr::ungroup() %>%
    dplyr::group_by(.data[[ind]]) %>%
    tidyr::pivot_wider(names_from = .data[[year]], values_from = .data[[type_col]]) %>%
    dplyr::ungroup() %>%
    dplyr::mutate(dplyr::across(dplyr::everything(), tidyr::replace_na, ""))

  args <- list("type" = list("reported", "projected", "imputed", ""),
               "fontColour" = list(NULL, "grey", "grey", NULL),
               "textDecoration" = list("bold", NULL, NULL, NULL))

  purrr::pwalk(args,
               type_styler,
               wb = wb,
               df = wide_df,
               sheet_name = sheet_name,
               start_row = start_row,
               start_col = start_col)
}


#' Generate a style with variable color or bolding
#'
#' `add_style_wrapper()` adds a style for use within [timeseries_style()],
#' where the font color and decoration needs to vary based on data type. Wraps
#' around [openxlsx::addStyle()] and [openxlsx::createStyle()].
#'
#' @inheritParams timeseries_style
#' @param rows Rows to apply style to, passed to `openxlsx::add_style()`.
#' @param cols Columns to apply style to, passed to `openxlsx::add_style()`.
#' @param fontColour Font colour, passed to [openxlsx::createStyle()].
#' @param textDecoration Font decoration, passed to [openxlsx::createStyle()].
add_style_wrapper <- function(wb,
                              sheet_name,
                              rows,
                              cols,
                              fontColour,
                              textDecoration) {
  openxlsx::addStyle(
    wb,
    sheet = sheet_name,
    rows = rows,
    cols = cols,
    style = openxlsx::createStyle(
      fontName = "Helvetica",
      fontColour = fontColour,
      textDecoration = textDecoration,
      fontSize = 8,
      halign = "left",
      wrapText = TRUE,
      numFmt = "0.00",
      border = "bottom"
    )
  )
}

#' @inheritParams add_style_wrapper
#' @inheritParams timeseries_style
type_styler <- function(wb,
                        sheet_name,
                        df,
                        type,
                        start_row,
                        start_col,
                        ind,
                        fontColour,
                        textDecoration) {
  # map across matching row/column values
  inds <- which(df == type, arr.ind = TRUE)
  inds_list <- split(inds[,2], inds[,1])

  purrr::iwalk(inds_list,
               ~ add_style_wrapper(
                 wb = wb,
                 sheet_name = sheet_name,
                 rows = as.numeric(.y) + start_row,
                 cols = .x + start_col-1,
                 fontColour = fontColour,
                 textDecoration = textDecoration
               ))
}

#' Styles HPOP time series
#'
#' @inheritParams write_hpop_timeseries_sheet
#' @param df_wide wide version of `df` generated by `write_hpop_timeseries_sheet`

style_hpop_timeseries <- function(df, wb, sheet_name, start_row, start_col, ind,
                                  year, type_col, df_wide){

  openxlsx::mergeCells(wb, sheet = sheet_name,
                       cols = start_col, rows = start_row:(start_row+1))

  openxlsx::mergeCells(wb, sheet = sheet_name,
                       cols = (start_col+1):(ncol(df_wide)), rows = start_row)

  openxlsx::addStyle(wb,
                     sheet = sheet_name, style = excel_styles()$dark_blue_header,
                     rows =start_row, cols = c(start_col:(ncol(df_wide)))
  )
  openxlsx::addStyle(wb,
                     sheet = sheet_name, style = excel_styles()$dark_blue_header,
                     rows = start_row:(start_row+1), cols = start_col
  )
  openxlsx::addStyle(wb,
                     sheet = sheet_name, style = excel_styles()$light_blue_header,
                     rows = c((start_row+1)), cols = c((start_col+1):(ncol(df_wide))),
                     gridExpand = TRUE
  )
  openxlsx::addStyle(wb,
                     sheet = sheet_name, style = excel_styles()$normal_data_wrapped_dec,
                     rows = c((start_row+2):(start_row+nrow(df_wide)+1)), cols = c(start_col:(ncol(df_wide))),
                     gridExpand = TRUE
  )
  timeseries_style(df, wb, sheet_name, start_row = start_row+1 , start_col = start_col,
                   ind, year, type_col)

  return(wb)
}

