# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
  pull_request:
    branches: main

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.PAT_GITHUB}}
      EXECUTION_MODE: "interactive"
      AZURE_CLIENT_ID: ${{ secrets.WHDH_APP_ID }}
      TENANT_ID: ${{ secrets.WHDH_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.WHDH_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
